### ISSUE TITLE
value binding issue

### ISSUE THREAD

**Issue by zimt28** [dalgard/meteor-viewmodel#13]
When using the `value` binding on an input field, the cursor will always jump to the end of the input when changes have been made. This is just noticeable when you try to edit the input not at the end, but in the middle or so.

**Comment by dalgard** [comment]
This is a serious flaw – I'll look into it right away. Thanks for reporting.

**Comment by dalgard** [comment]
Fixed in `0.8.3`.

From this version, the `set` function in the binding is not triggered if the property is updated after an event, i.e. after `get`. This behavior can be controlled via `this.preventSet()` (as in the case with the `value` binding, where the property is updated directly inside `get`) – or `this.preventSet(false)` if the binding does wish to trigger `set` after `get`.

**Comment by Saduff** [comment]
I still have this problem in version 1.0.1_1 using Meteor 1.2.1. Ctrl+A to select all doesn't work also.

**Comment by dalgard** [comment]
Must be a regression. Will fix it right away.

**Comment by dalgard** [comment]
This regression is fixed in `1.0.2`. (I had unintentionally triggered a Tracker flush at the wrong time.)

**Comment by Saduff** [comment]
Wow, that was fast. Thanks a lot for the package and the quick fix. :)

**Comment by dalgard** [comment]
If you don't mind my curiosity, what are you using the package for? Feel free to create new issues with any further questions.

**Comment by Saduff** [comment]
I come from PHP and KnockoutJS, Node and Meteor are quite new to me, only recently started with Meteor. I first tried with only Blaze, but then found the manuel:viewmodel package and thought it would be a good addition. It was good except for one thing which I thought it had - persistence across routes/re-renders. That's an essential thing for me and I'm glad it's in this package. The migration was painless as well.
